numero = int(input('Digite um número: '))
antecessor = (numero - 1)
sucessor = (numero + 1)
print('Analisando o valor {}, posso afirmar que seu antecessor é {} e o sucessor é {}'.format(numero, antecessor, sucessor))
print('Analisando o valor {}, posso afirmar que seu antecessor é {} e o sucessor é {}'.format(numero, numero-1, numero+1))
